test:
        image: "python:2.7"
        stage: test
        script:
                - pip install -r requirements.txt
                - pip install -r test_requirments.txt
                - PYTHONPATH=. py.test --verbose -s
